import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faHouse,
  faHouseChimney,
  faBed,
  faCouch,
  faBath,
  faToilet,
  faKitchenSet,
  faBlender,
  faSoap,
  faBroom,
  faLightbulb,
  faPlug,
  faFireExtinguisher,
  faKey,
  faDoorOpen,
  faStairs,
  faWarehouse,
  faBuilding,
  faCity,
  faTree,
  faUtensils,
  faBurger,
  faPizzaSlice,
  faDrumstickBite,
  faFish,
  faCarrot,
  faAppleWhole,
  faBreadSlice,
  faCheese,
  faEgg,
  faIceCream,
  faCakeCandles,
  faCookieBite,
  faMugSaucer,
  faMugHot,
  faWineGlass,
  faBeerMugEmpty,
  faMartiniGlass,
  faBottleWater,
  faBowlFood,
  faCartShopping,
  faBasketShopping,
  faBagShopping,
  faStore,
  faTag,
  faTags,
  faReceipt,
  faBarcode,
  faGift,
  faShirt,
  faShoePrints,
  faGlasses,
  faGem,
  faCar,
  faCarSide,
  faTaxi,
  faBus,
  faTrainSubway,
  faTrain,
  faBicycle,
  faMotorcycle,
  faTruck,
  faGasPump,
  faChargingStation,
  faParking,
  faRoad,
  faTicket,
  faHelmetSafety,
  faCarBurst,
  faPlane,
  faPlaneDeparture,
  faSuitcase,
  faSuitcaseRolling,
  faPassport,
  faEarthAmericas,
  faMapLocationDot,
  faUmbrellaBeach,
  faMountainSun,
  faCampground,
  faHotel,
  faShip,
  faAnchor,
  faCompass,
  faFilm,
  faTicketSimple,
  faMusic,
  faGuitar,
  faHeadphones,
  faGamepad,
  faDice,
  faPuzzlePiece,
  faFutbol,
  faBasketball,
  faPersonSwimming,
  faPersonHiking,
  faPersonSkiing,
  faDumbbell,
  faSpa,
  faPalette,
  faCamera,
  faBookOpen,
  faMicrophone,
  faKitMedical,
  faPills,
  faStethoscope,
  faTooth,
  faHeartPulse,
  faHospital,
  faUserDoctor,
  faSyringe,
  faGlassWater,
  faFileInvoiceDollar,
  faFileLines,
  faBolt,
  faDroplet,
  faFire,
  faWifi,
  faTowerBroadcast,
  faMobileScreen,
  faTv,
  faSatelliteDish,
  faShieldHalved,
  faRecycle,
  faTrash,
  faMoneyBill,
  faMoneyBillWave,
  faMoneyBillTransfer,
  faWallet,
  faCreditCard,
  faCoins,
  faPiggyBank,
  faHandHoldingDollar,
  faBuildingColumns,
  faChartLine,
  faChartPie,
  faPercent,
  faSackDollar,
  faScaleBalanced,
  faCalculator,
  faUser,
  faUsers,
  faUserGroup,
  faChild,
  faBabyCarriage,
  faPaw,
  faDog,
  faCat,
  faHandshake,
  faHeart,
  faRing,
  faGraduationCap,
  faBriefcase,
  faPersonCane,
  faStar,
  faFlag,
  faBell,
  faCalendarDays,
  faClock,
  faLocationDot,
  faPaperclip,
  faBox,
  faBoxesStacked,
  faWrench,
  faScrewdriverWrench,
  faSeedling,
  faLeaf,
  faSun,
  faSnowflake,
  faUmbrella,
  faCircleQuestion,
  faEllipsis,
} from '@fortawesome/free-solid-svg-icons'

/**
 * The icons a group can be given.
 *
 * A curated set rather than all two thousand Font Awesome solid icons, for two
 * reasons: importing them all costs about a megabyte of JavaScript in an app that
 * has to work offline, and a picker showing two thousand results is harder to use
 * than one showing the hundred and seventy that mean something for shared costs.
 *
 * Every icon carries a human label and keywords, because people search for what a
 * thing is rather than what it is called: "home" has to find the house, and
 * "hydro" has to find the electricity bolt.
 *
 * The stored value is the Font Awesome name, so it is stable, readable in the
 * database, and independent of this list.
 */
export interface IconChoice {
  /** Font Awesome name. This is what gets stored. */
  name: string
  /** What it means here, which is not always what Font Awesome calls it. */
  label: string
  /** Other words someone might search for. */
  keywords: readonly string[]
  /** Section heading in the picker. */
  group: string
  definition: IconDefinition
}

export const ICON_GROUPS: readonly string[] = [
  'Home',
  'Food and drink',
  'Shopping',
  'Transport',
  'Travel',
  'Fun',
  'Health',
  'Bills',
  'Money',
  'People',
  'Other',
]

export const ICONS: readonly IconChoice[] = [
  { name: faHouse.iconName, label: 'House', keywords: ['home', 'flat', 'apartment', 'rent', 'place'], group: 'Home', definition: faHouse },
  { name: faHouseChimney.iconName, label: 'Home', keywords: ['house', 'cottage', 'mortgage'], group: 'Home', definition: faHouseChimney },
  { name: faBed.iconName, label: 'Bed', keywords: ['bedroom', 'sleep', 'mattress', 'hotel'], group: 'Home', definition: faBed },
  { name: faCouch.iconName, label: 'Couch', keywords: ['sofa', 'furniture', 'living room', 'lounge'], group: 'Home', definition: faCouch },
  { name: faBath.iconName, label: 'Bath', keywords: ['bathroom', 'shower', 'tub', 'washroom'], group: 'Home', definition: faBath },
  { name: faToilet.iconName, label: 'Toilet', keywords: ['bathroom', 'washroom', 'plumbing'], group: 'Home', definition: faToilet },
  { name: faKitchenSet.iconName, label: 'Kitchen', keywords: ['cooking', 'pots', 'pans', 'utensils'], group: 'Home', definition: faKitchenSet },
  { name: faBlender.iconName, label: 'Blender', keywords: ['appliance', 'kitchen', 'smoothie'], group: 'Home', definition: faBlender },
  { name: faSoap.iconName, label: 'Cleaning', keywords: ['soap', 'detergent', 'laundry', 'supplies'], group: 'Home', definition: faSoap },
  { name: faBroom.iconName, label: 'Chores', keywords: ['broom', 'sweep', 'cleaning', 'tidy'], group: 'Home', definition: faBroom },
  { name: faLightbulb.iconName, label: 'Light', keywords: ['bulb', 'lamp', 'electricity', 'idea'], group: 'Home', definition: faLightbulb },
  { name: faPlug.iconName, label: 'Appliance', keywords: ['plug', 'power', 'electric', 'socket'], group: 'Home', definition: faPlug },
  { name: faFireExtinguisher.iconName, label: 'Safety', keywords: ['extinguisher', 'fire', 'emergency'], group: 'Home', definition: faFireExtinguisher },
  { name: faKey.iconName, label: 'Keys', keywords: ['lock', 'deposit', 'landlord', 'access'], group: 'Home', definition: faKey },
  { name: faDoorOpen.iconName, label: 'Moving in', keywords: ['door', 'entrance', 'keys', 'move'], group: 'Home', definition: faDoorOpen },
  { name: faStairs.iconName, label: 'Stairs', keywords: ['steps', 'building', 'floor'], group: 'Home', definition: faStairs },
  { name: faWarehouse.iconName, label: 'Storage', keywords: ['warehouse', 'unit', 'locker'], group: 'Home', definition: faWarehouse },
  { name: faBuilding.iconName, label: 'Building', keywords: ['office', 'apartment', 'block'], group: 'Home', definition: faBuilding },
  { name: faCity.iconName, label: 'City', keywords: ['town', 'urban', 'skyline'], group: 'Home', definition: faCity },
  { name: faTree.iconName, label: 'Garden', keywords: ['tree', 'yard', 'plants', 'outdoors'], group: 'Home', definition: faTree },
  { name: faUtensils.iconName, label: 'Restaurant', keywords: ['dining', 'eat', 'food', 'fork', 'knife', 'meal'], group: 'Food and drink', definition: faUtensils },
  { name: faBurger.iconName, label: 'Burger', keywords: ['fast food', 'takeaway', 'lunch'], group: 'Food and drink', definition: faBurger },
  { name: faPizzaSlice.iconName, label: 'Pizza', keywords: ['takeaway', 'italian', 'delivery'], group: 'Food and drink', definition: faPizzaSlice },
  { name: faDrumstickBite.iconName, label: 'Chicken', keywords: ['meat', 'poultry', 'dinner'], group: 'Food and drink', definition: faDrumstickBite },
  { name: faFish.iconName, label: 'Fish', keywords: ['seafood', 'sushi', 'market'], group: 'Food and drink', definition: faFish },
  { name: faCarrot.iconName, label: 'Vegetables', keywords: ['carrot', 'veg', 'produce', 'greens'], group: 'Food and drink', definition: faCarrot },
  { name: faAppleWhole.iconName, label: 'Fruit', keywords: ['apple', 'produce', 'healthy'], group: 'Food and drink', definition: faAppleWhole },
  { name: faBreadSlice.iconName, label: 'Bakery', keywords: ['bread', 'loaf', 'baking'], group: 'Food and drink', definition: faBreadSlice },
  { name: faCheese.iconName, label: 'Cheese', keywords: ['dairy', 'deli'], group: 'Food and drink', definition: faCheese },
  { name: faEgg.iconName, label: 'Eggs', keywords: ['breakfast', 'dairy'], group: 'Food and drink', definition: faEgg },
  { name: faIceCream.iconName, label: 'Dessert', keywords: ['ice cream', 'sweet', 'treat'], group: 'Food and drink', definition: faIceCream },
  { name: faCakeCandles.iconName, label: 'Cake', keywords: ['birthday', 'celebration', 'dessert'], group: 'Food and drink', definition: faCakeCandles },
  { name: faCookieBite.iconName, label: 'Snacks', keywords: ['cookie', 'biscuit', 'treat'], group: 'Food and drink', definition: faCookieBite },
  { name: faMugSaucer.iconName, label: 'Cafe', keywords: ['coffee', 'tea', 'espresso', 'cup'], group: 'Food and drink', definition: faMugSaucer },
  { name: faMugHot.iconName, label: 'Hot drink', keywords: ['tea', 'coffee', 'cocoa'], group: 'Food and drink', definition: faMugHot },
  { name: faWineGlass.iconName, label: 'Wine', keywords: ['bar', 'alcohol', 'drinks'], group: 'Food and drink', definition: faWineGlass },
  { name: faBeerMugEmpty.iconName, label: 'Beer', keywords: ['pub', 'bar', 'drinks', 'pint'], group: 'Food and drink', definition: faBeerMugEmpty },
  { name: faMartiniGlass.iconName, label: 'Cocktails', keywords: ['bar', 'drinks', 'night out'], group: 'Food and drink', definition: faMartiniGlass },
  { name: faBottleWater.iconName, label: 'Water', keywords: ['bottle', 'drink', 'hydration'], group: 'Food and drink', definition: faBottleWater },
  { name: faBowlFood.iconName, label: 'Meal', keywords: ['bowl', 'lunch', 'dinner', 'soup'], group: 'Food and drink', definition: faBowlFood },
  { name: faCartShopping.iconName, label: 'Groceries', keywords: ['cart', 'shopping', 'supermarket', 'food shop'], group: 'Shopping', definition: faCartShopping },
  { name: faBasketShopping.iconName, label: 'Basket', keywords: ['shopping', 'groceries', 'market'], group: 'Shopping', definition: faBasketShopping },
  { name: faBagShopping.iconName, label: 'Shopping', keywords: ['bag', 'retail', 'purchase'], group: 'Shopping', definition: faBagShopping },
  { name: faStore.iconName, label: 'Shop', keywords: ['store', 'retail', 'market'], group: 'Shopping', definition: faStore },
  { name: faTag.iconName, label: 'Price', keywords: ['tag', 'label', 'sale', 'discount'], group: 'Shopping', definition: faTag },
  { name: faTags.iconName, label: 'Sale', keywords: ['tags', 'discount', 'offers'], group: 'Shopping', definition: faTags },
  { name: faReceipt.iconName, label: 'Receipt', keywords: ['bill', 'proof', 'expense'], group: 'Shopping', definition: faReceipt },
  { name: faBarcode.iconName, label: 'Product', keywords: ['barcode', 'scan', 'item'], group: 'Shopping', definition: faBarcode },
  { name: faGift.iconName, label: 'Gift', keywords: ['present', 'birthday', 'celebration'], group: 'Shopping', definition: faGift },
  { name: faShirt.iconName, label: 'Clothes', keywords: ['shirt', 'clothing', 'laundry', 'apparel'], group: 'Shopping', definition: faShirt },
  { name: faShoePrints.iconName, label: 'Shoes', keywords: ['footwear', 'sneakers'], group: 'Shopping', definition: faShoePrints },
  { name: faGlasses.iconName, label: 'Glasses', keywords: ['eyewear', 'optician', 'spectacles'], group: 'Shopping', definition: faGlasses },
  { name: faGem.iconName, label: 'Jewellery', keywords: ['gem', 'ring', 'luxury', 'diamond'], group: 'Shopping', definition: faGem },
  { name: faCar.iconName, label: 'Car', keywords: ['drive', 'vehicle', 'auto', 'petrol'], group: 'Transport', definition: faCar },
  { name: faCarSide.iconName, label: 'Car trip', keywords: ['drive', 'vehicle', 'road trip'], group: 'Transport', definition: faCarSide },
  { name: faTaxi.iconName, label: 'Taxi', keywords: ['cab', 'uber', 'ride', 'lyft'], group: 'Transport', definition: faTaxi },
  { name: faBus.iconName, label: 'Bus', keywords: ['transit', 'coach', 'public transport'], group: 'Transport', definition: faBus },
  { name: faTrainSubway.iconName, label: 'Metro', keywords: ['subway', 'underground', 'tube', 'transit'], group: 'Transport', definition: faTrainSubway },
  { name: faTrain.iconName, label: 'Train', keywords: ['rail', 'commute', 'transit'], group: 'Transport', definition: faTrain },
  { name: faBicycle.iconName, label: 'Bike', keywords: ['bicycle', 'cycling', 'ride'], group: 'Transport', definition: faBicycle },
  { name: faMotorcycle.iconName, label: 'Motorbike', keywords: ['scooter', 'moped', 'ride'], group: 'Transport', definition: faMotorcycle },
  { name: faTruck.iconName, label: 'Delivery', keywords: ['truck', 'shipping', 'freight', 'moving'], group: 'Transport', definition: faTruck },
  { name: faGasPump.iconName, label: 'Fuel', keywords: ['petrol', 'gas', 'diesel', 'fill up'], group: 'Transport', definition: faGasPump },
  { name: faChargingStation.iconName, label: 'Charging', keywords: ['ev', 'electric', 'charge'], group: 'Transport', definition: faChargingStation },
  { name: faParking.iconName, label: 'Parking', keywords: ['car park', 'garage', 'meter'], group: 'Transport', definition: faParking },
  { name: faRoad.iconName, label: 'Toll', keywords: ['road', 'highway', 'motorway'], group: 'Transport', definition: faRoad },
  { name: faTicket.iconName, label: 'Ticket', keywords: ['fare', 'pass', 'entry'], group: 'Transport', definition: faTicket },
  { name: faHelmetSafety.iconName, label: 'Repairs', keywords: ['helmet', 'work', 'maintenance'], group: 'Transport', definition: faHelmetSafety },
  { name: faCarBurst.iconName, label: 'Car repair', keywords: ['garage', 'mechanic', 'accident', 'bodywork'], group: 'Transport', definition: faCarBurst },
  { name: faPlane.iconName, label: 'Flight', keywords: ['plane', 'airline', 'airfare', 'travel'], group: 'Travel', definition: faPlane },
  { name: faPlaneDeparture.iconName, label: 'Departure', keywords: ['plane', 'airport', 'trip'], group: 'Travel', definition: faPlaneDeparture },
  { name: faSuitcase.iconName, label: 'Luggage', keywords: ['suitcase', 'baggage', 'trip'], group: 'Travel', definition: faSuitcase },
  { name: faSuitcaseRolling.iconName, label: 'Trip', keywords: ['suitcase', 'holiday', 'vacation'], group: 'Travel', definition: faSuitcaseRolling },
  { name: faPassport.iconName, label: 'Passport', keywords: ['visa', 'documents', 'travel'], group: 'Travel', definition: faPassport },
  { name: faEarthAmericas.iconName, label: 'Abroad', keywords: ['world', 'globe', 'international'], group: 'Travel', definition: faEarthAmericas },
  { name: faMapLocationDot.iconName, label: 'Map', keywords: ['location', 'directions', 'navigation'], group: 'Travel', definition: faMapLocationDot },
  { name: faUmbrellaBeach.iconName, label: 'Beach', keywords: ['holiday', 'vacation', 'sun', 'seaside'], group: 'Travel', definition: faUmbrellaBeach },
  { name: faMountainSun.iconName, label: 'Hiking trip', keywords: ['mountain', 'outdoors', 'nature'], group: 'Travel', definition: faMountainSun },
  { name: faCampground.iconName, label: 'Camping', keywords: ['tent', 'outdoors', 'campsite'], group: 'Travel', definition: faCampground },
  { name: faHotel.iconName, label: 'Hotel', keywords: ['accommodation', 'stay', 'lodging', 'airbnb'], group: 'Travel', definition: faHotel },
  { name: faShip.iconName, label: 'Ferry', keywords: ['boat', 'cruise', 'ship'], group: 'Travel', definition: faShip },
  { name: faAnchor.iconName, label: 'Boat', keywords: ['anchor', 'marina', 'sailing'], group: 'Travel', definition: faAnchor },
  { name: faCompass.iconName, label: 'Excursion', keywords: ['compass', 'tour', 'explore'], group: 'Travel', definition: faCompass },
  { name: faFilm.iconName, label: 'Cinema', keywords: ['movie', 'film', 'theatre'], group: 'Fun', definition: faFilm },
  { name: faTicketSimple.iconName, label: 'Event', keywords: ['ticket', 'concert', 'entry', 'show'], group: 'Fun', definition: faTicketSimple },
  { name: faMusic.iconName, label: 'Music', keywords: ['song', 'concert', 'spotify', 'streaming'], group: 'Fun', definition: faMusic },
  { name: faGuitar.iconName, label: 'Instrument', keywords: ['guitar', 'music', 'lessons'], group: 'Fun', definition: faGuitar },
  { name: faHeadphones.iconName, label: 'Audio', keywords: ['headphones', 'podcast', 'streaming', 'spotify'], group: 'Fun', definition: faHeadphones },
  { name: faGamepad.iconName, label: 'Games', keywords: ['gaming', 'console', 'video games'], group: 'Fun', definition: faGamepad },
  { name: faDice.iconName, label: 'Board games', keywords: ['dice', 'games', 'night in'], group: 'Fun', definition: faDice },
  { name: faPuzzlePiece.iconName, label: 'Hobby', keywords: ['puzzle', 'craft', 'pastime'], group: 'Fun', definition: faPuzzlePiece },
  { name: faFutbol.iconName, label: 'Football', keywords: ['soccer', 'sport', 'ball'], group: 'Fun', definition: faFutbol },
  { name: faBasketball.iconName, label: 'Basketball', keywords: ['sport', 'ball', 'court'], group: 'Fun', definition: faBasketball },
  { name: faPersonSwimming.iconName, label: 'Swimming', keywords: ['pool', 'swim', 'sport'], group: 'Fun', definition: faPersonSwimming },
  { name: faPersonHiking.iconName, label: 'Hiking', keywords: ['walk', 'trail', 'outdoors'], group: 'Fun', definition: faPersonHiking },
  { name: faPersonSkiing.iconName, label: 'Skiing', keywords: ['ski', 'snow', 'winter', 'slopes'], group: 'Fun', definition: faPersonSkiing },
  { name: faDumbbell.iconName, label: 'Gym', keywords: ['fitness', 'workout', 'membership', 'exercise'], group: 'Fun', definition: faDumbbell },
  { name: faSpa.iconName, label: 'Spa', keywords: ['massage', 'wellness', 'relax'], group: 'Fun', definition: faSpa },
  { name: faPalette.iconName, label: 'Art', keywords: ['paint', 'craft', 'creative', 'class'], group: 'Fun', definition: faPalette },
  { name: faCamera.iconName, label: 'Photos', keywords: ['camera', 'photography', 'pictures'], group: 'Fun', definition: faCamera },
  { name: faBookOpen.iconName, label: 'Books', keywords: ['reading', 'book', 'library', 'course'], group: 'Fun', definition: faBookOpen },
  { name: faMicrophone.iconName, label: 'Karaoke', keywords: ['microphone', 'singing', 'night out'], group: 'Fun', definition: faMicrophone },
  { name: faKitMedical.iconName, label: 'First aid', keywords: ['medical', 'kit', 'health'], group: 'Health', definition: faKitMedical },
  { name: faPills.iconName, label: 'Medicine', keywords: ['pills', 'pharmacy', 'prescription', 'drugs'], group: 'Health', definition: faPills },
  { name: faStethoscope.iconName, label: 'Doctor', keywords: ['clinic', 'gp', 'appointment', 'health'], group: 'Health', definition: faStethoscope },
  { name: faTooth.iconName, label: 'Dentist', keywords: ['tooth', 'dental', 'teeth'], group: 'Health', definition: faTooth },
  { name: faHeartPulse.iconName, label: 'Health', keywords: ['heart', 'wellbeing', 'checkup'], group: 'Health', definition: faHeartPulse },
  { name: faHospital.iconName, label: 'Hospital', keywords: ['clinic', 'emergency', 'care'], group: 'Health', definition: faHospital },
  { name: faUserDoctor.iconName, label: 'Specialist', keywords: ['doctor', 'consultation', 'appointment'], group: 'Health', definition: faUserDoctor },
  { name: faSyringe.iconName, label: 'Vaccine', keywords: ['injection', 'shot', 'jab'], group: 'Health', definition: faSyringe },
  { name: faGlassWater.iconName, label: 'Hydration', keywords: ['water', 'glass', 'drink'], group: 'Health', definition: faGlassWater },
  { name: faFileInvoiceDollar.iconName, label: 'Invoice', keywords: ['bill', 'statement', 'account'], group: 'Bills', definition: faFileInvoiceDollar },
  { name: faFileLines.iconName, label: 'Document', keywords: ['paperwork', 'form', 'admin'], group: 'Bills', definition: faFileLines },
  { name: faBolt.iconName, label: 'Electricity', keywords: ['power', 'hydro', 'energy', 'bolt'], group: 'Bills', definition: faBolt },
  { name: faDroplet.iconName, label: 'Water bill', keywords: ['water', 'utility', 'plumbing'], group: 'Bills', definition: faDroplet },
  { name: faFire.iconName, label: 'Gas', keywords: ['heating', 'fire', 'energy'], group: 'Bills', definition: faFire },
  { name: faWifi.iconName, label: 'Internet', keywords: ['wifi', 'broadband', 'router', 'connection'], group: 'Bills', definition: faWifi },
  { name: faTowerBroadcast.iconName, label: 'Mobile', keywords: ['signal', 'network', 'phone plan'], group: 'Bills', definition: faTowerBroadcast },
  { name: faMobileScreen.iconName, label: 'Phone', keywords: ['mobile', 'cell', 'handset', 'plan'], group: 'Bills', definition: faMobileScreen },
  { name: faTv.iconName, label: 'TV', keywords: ['television', 'streaming', 'cable', 'licence', 'netflix', 'disney'], group: 'Bills', definition: faTv },
  { name: faSatelliteDish.iconName, label: 'Satellite', keywords: ['dish', 'tv', 'signal'], group: 'Bills', definition: faSatelliteDish },
  { name: faShieldHalved.iconName, label: 'Insurance', keywords: ['shield', 'cover', 'policy', 'protection'], group: 'Bills', definition: faShieldHalved },
  { name: faRecycle.iconName, label: 'Recycling', keywords: ['waste', 'bins', 'environment'], group: 'Bills', definition: faRecycle },
  { name: faTrash.iconName, label: 'Waste', keywords: ['bins', 'rubbish', 'garbage', 'collection'], group: 'Bills', definition: faTrash },
  { name: faMoneyBill.iconName, label: 'Cash', keywords: ['money', 'notes', 'bill', 'currency'], group: 'Money', definition: faMoneyBill },
  { name: faMoneyBillWave.iconName, label: 'Payment', keywords: ['money', 'cash', 'paid'], group: 'Money', definition: faMoneyBillWave },
  { name: faMoneyBillTransfer.iconName, label: 'Transfer', keywords: ['send', 'etransfer', 'payment', 'settle'], group: 'Money', definition: faMoneyBillTransfer },
  { name: faWallet.iconName, label: 'Wallet', keywords: ['money', 'cash', 'pocket', 'spending'], group: 'Money', definition: faWallet },
  { name: faCreditCard.iconName, label: 'Card', keywords: ['credit', 'debit', 'payment', 'visa'], group: 'Money', definition: faCreditCard },
  { name: faCoins.iconName, label: 'Change', keywords: ['coins', 'cash', 'small change'], group: 'Money', definition: faCoins },
  { name: faPiggyBank.iconName, label: 'Savings', keywords: ['save', 'bank', 'fund'], group: 'Money', definition: faPiggyBank },
  { name: faHandHoldingDollar.iconName, label: 'Lending', keywords: ['loan', 'borrow', 'lend', 'owed'], group: 'Money', definition: faHandHoldingDollar },
  { name: faBuildingColumns.iconName, label: 'Bank', keywords: ['bank', 'institution', 'account'], group: 'Money', definition: faBuildingColumns },
  { name: faChartLine.iconName, label: 'Spending', keywords: ['chart', 'trend', 'graph', 'stats'], group: 'Money', definition: faChartLine },
  { name: faChartPie.iconName, label: 'Breakdown', keywords: ['chart', 'pie', 'split', 'share'], group: 'Money', definition: faChartPie },
  { name: faPercent.iconName, label: 'Interest', keywords: ['percent', 'rate', 'fee'], group: 'Money', definition: faPercent },
  { name: faSackDollar.iconName, label: 'Fund', keywords: ['money', 'pot', 'kitty', 'budget'], group: 'Money', definition: faSackDollar },
  { name: faScaleBalanced.iconName, label: 'Settled', keywords: ['balance', 'fair', 'even', 'scales'], group: 'Money', definition: faScaleBalanced },
  { name: faCalculator.iconName, label: 'Split', keywords: ['calculate', 'maths', 'divide'], group: 'Money', definition: faCalculator },
  { name: faUser.iconName, label: 'Person', keywords: ['user', 'individual', 'someone'], group: 'People', definition: faUser },
  { name: faUsers.iconName, label: 'People', keywords: ['group', 'team', 'friends'], group: 'People', definition: faUsers },
  { name: faUserGroup.iconName, label: 'Group', keywords: ['people', 'housemates', 'flatmates', 'team'], group: 'People', definition: faUserGroup },
  { name: faChild.iconName, label: 'Kids', keywords: ['child', 'children', 'family'], group: 'People', definition: faChild },
  { name: faBabyCarriage.iconName, label: 'Baby', keywords: ['pram', 'stroller', 'childcare'], group: 'People', definition: faBabyCarriage },
  { name: faPaw.iconName, label: 'Pets', keywords: ['paw', 'animal', 'vet'], group: 'People', definition: faPaw },
  { name: faDog.iconName, label: 'Dog', keywords: ['pet', 'animal', 'walk'], group: 'People', definition: faDog },
  { name: faCat.iconName, label: 'Cat', keywords: ['pet', 'animal', 'litter'], group: 'People', definition: faCat },
  { name: faHandshake.iconName, label: 'Shared', keywords: ['agreement', 'deal', 'together'], group: 'People', definition: faHandshake },
  { name: faHeart.iconName, label: 'Favourite', keywords: ['love', 'heart', 'like'], group: 'People', definition: faHeart },
  { name: faRing.iconName, label: 'Wedding', keywords: ['ring', 'marriage', 'engagement'], group: 'People', definition: faRing },
  { name: faGraduationCap.iconName, label: 'Studies', keywords: ['school', 'university', 'tuition', 'course'], group: 'People', definition: faGraduationCap },
  { name: faBriefcase.iconName, label: 'Work', keywords: ['business', 'office', 'job', 'expenses'], group: 'People', definition: faBriefcase },
  { name: faPersonCane.iconName, label: 'Care', keywords: ['elderly', 'support', 'assistance'], group: 'People', definition: faPersonCane },
  { name: faStar.iconName, label: 'Starred', keywords: ['favourite', 'important', 'star'], group: 'Other', definition: faStar },
  { name: faFlag.iconName, label: 'Flag', keywords: ['marker', 'country', 'milestone'], group: 'Other', definition: faFlag },
  { name: faBell.iconName, label: 'Reminder', keywords: ['notification', 'alert', 'bell'], group: 'Other', definition: faBell },
  { name: faCalendarDays.iconName, label: 'Recurring', keywords: ['calendar', 'monthly', 'schedule', 'date'], group: 'Other', definition: faCalendarDays },
  { name: faClock.iconName, label: 'Time', keywords: ['hours', 'clock', 'duration'], group: 'Other', definition: faClock },
  { name: faLocationDot.iconName, label: 'Place', keywords: ['location', 'pin', 'address', 'where'], group: 'Other', definition: faLocationDot },
  { name: faPaperclip.iconName, label: 'Attachment', keywords: ['clip', 'file', 'attached'], group: 'Other', definition: faPaperclip },
  { name: faBox.iconName, label: 'Package', keywords: ['box', 'parcel', 'delivery'], group: 'Other', definition: faBox },
  { name: faBoxesStacked.iconName, label: 'Moving', keywords: ['boxes', 'relocation', 'storage'], group: 'Other', definition: faBoxesStacked },
  { name: faWrench.iconName, label: 'Repair', keywords: ['wrench', 'fix', 'maintenance'], group: 'Other', definition: faWrench },
  { name: faScrewdriverWrench.iconName, label: 'Maintenance', keywords: ['tools', 'diy', 'repairs'], group: 'Other', definition: faScrewdriverWrench },
  { name: faSeedling.iconName, label: 'Plants', keywords: ['seedling', 'garden', 'grow'], group: 'Other', definition: faSeedling },
  { name: faLeaf.iconName, label: 'Green', keywords: ['leaf', 'eco', 'nature'], group: 'Other', definition: faLeaf },
  { name: faSun.iconName, label: 'Summer', keywords: ['sun', 'weather', 'warm'], group: 'Other', definition: faSun },
  { name: faSnowflake.iconName, label: 'Winter', keywords: ['snow', 'cold', 'heating'], group: 'Other', definition: faSnowflake },
  { name: faUmbrella.iconName, label: 'Rain', keywords: ['umbrella', 'weather', 'wet'], group: 'Other', definition: faUmbrella },
  { name: faCircleQuestion.iconName, label: 'Unsorted', keywords: ['question', 'unknown', 'other'], group: 'Other', definition: faCircleQuestion },
  { name: faEllipsis.iconName, label: 'Other', keywords: ['more', 'misc', 'miscellaneous'], group: 'Other', definition: faEllipsis },
]

/** The icon used when a group has none, so the UI never renders a hole. */
export const FALLBACK_ICON = ICONS.find((icon) => icon.label === 'Group') ?? ICONS[0]

const byName = new Map(ICONS.map((icon) => [icon.name, icon]))

export function findIcon(name: string | null | undefined): IconChoice | null {
  if (!name) return null
  return byName.get(name) ?? null
}

/**
 * Resolves a stored name to something renderable.
 *
 * Falls back rather than throwing: a name saved by a newer version of the app, or
 * removed from this list, must not break a group list.
 */
export function resolveIcon(name: string | null | undefined): IconChoice {
  return findIcon(name) ?? FALLBACK_ICON
}

/** The searchable fields of an icon, name last since it is the least human. */
export function iconSearchFields(icon: IconChoice): readonly string[] {
  return [icon.label, ...icon.keywords, icon.name]
}
