<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SplitEverything.Application\SplitEverything.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="WebPush" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
