// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplitEverything.Infrastructure.Persistence;

#nullable disable

namespace SplitEverything.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831181303_RenameIconColumns")]
    partial class RenameIconColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SplitEverything.Domain.Entities.ActivityLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_member_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<int?>("SubjectType")
                        .HasColumnType("integer")
                        .HasColumnName("subject_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_activity_log");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_activity_log_actor_user_id");

                    b.HasIndex("GroupId", "OccurredAt")
                        .HasDatabaseName("ix_activity_log_group_id_occurred_at");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color_hex");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("icon_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("OwnerUserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_owner_user_id_key");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.CategoryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("HitCount")
                        .HasColumnType("integer")
                        .HasColumnName("hit_count");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("keyword");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<Guid?>("SuggestedGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_category_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_rules_category_id");

                    b.HasIndex("UserId", "Keyword")
                        .IsUnique()
                        .HasDatabaseName("ix_category_rules_user_id_keyword");

                    b.ToTable("category_rules", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<long>("LastAckedServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_acked_server_seq");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExchangeRateSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quote_currency");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("rate");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.HasKey("Id")
                        .HasName("pk_exchange_rates");

                    b.HasIndex("BaseCurrency", "QuoteCurrency", "RateDate")
                        .IsUnique()
                        .HasDatabaseName("ix_exchange_rates_base_currency_quote_currency_rate_date");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountInBaseCurrency")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount_in_base_currency");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<DateTimeOffset?>("ExchangeRateAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exchange_rate_as_of");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<string>("ImportFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("import_fingerprint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OriginGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_group_id");

                    b.Property<Guid>("OriginLineageId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_lineage_id");

                    b.Property<Guid>("PaidByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_member_id");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<Guid?>("RecurringExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurring_expense_id");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<DateTimeOffset>("SpentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spent_at");

                    b.Property<int>("SplitType")
                        .HasColumnType("integer")
                        .HasColumnName("split_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_expenses_category_id");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_expenses_import_batch_id");

                    b.HasIndex("ImportFingerprint")
                        .HasDatabaseName("ix_expenses_import_fingerprint");

                    b.HasIndex("PaidByMemberId")
                        .HasDatabaseName("ix_expenses_paid_by_member_id");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_expenses_receipt_id");

                    b.HasIndex("RecurringExpenseId")
                        .HasDatabaseName("ix_expenses_recurring_expense_id");

                    b.HasIndex("GroupId", "ServerSeq")
                        .HasDatabaseName("ix_expenses_group_id_server_seq");

                    b.HasIndex("GroupId", "SpentAt")
                        .HasDatabaseName("ix_expenses_group_id_spent_at");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_member_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_expense_comments");

                    b.HasIndex("AuthorMemberId")
                        .HasDatabaseName("ix_expense_comments_author_member_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_expense_comments_group_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_expense_comments_parent_comment_id");

                    b.HasIndex("ExpenseId", "CreatedAt")
                        .HasDatabaseName("ix_expense_comments_expense_id_created_at");

                    b.ToTable("expense_comments", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_expense_items");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_expense_items_expense_id");

                    b.ToTable("expense_items", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseItemShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExpenseItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_item_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_item_shares");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_expense_item_shares_member_id");

                    b.HasIndex("ExpenseItemId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_expense_item_shares_expense_item_id_member_id");

                    b.ToTable("expense_item_shares", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_summary");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<string>("EditedByDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("edited_by_device_id");

                    b.Property<Guid?>("EditedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by_user_id");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_expense_revisions");

                    b.HasIndex("ExpenseId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_expense_revisions_expense_id_revision");

                    b.ToTable("expense_revisions", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountInBaseCurrency")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount_in_base_currency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<decimal?>("InputValue")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("input_value");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_expense_splits");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_expense_splits_group_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_expense_splits_member_id");

                    b.HasIndex("ExpenseId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_expense_splits_expense_id_member_id");

                    b.ToTable("expense_splits", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color_hex");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("IconName")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("icon_name");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<Guid>("LineageId")
                        .HasColumnType("uuid")
                        .HasColumnName("lineage_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("SequenceCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_counter");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_groups_created_by_user_id");

                    b.HasIndex("LineageId")
                        .HasDatabaseName("ix_groups_lineage_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.GroupInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClaimsMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("claims_member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_email");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id")
                        .HasName("pk_group_invites");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_invites_group_id");

                    b.HasIndex("InvitedEmail")
                        .HasDatabaseName("ix_group_invites_invited_email");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_group_invites_token_hash");

                    b.ToTable("group_invites", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.GroupLineageLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("MovedLineageId")
                        .HasColumnType("uuid")
                        .HasColumnName("moved_lineage_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("SourceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_group_id");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_group_id");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_group_lineage_links");

                    b.HasIndex("MovedLineageId")
                        .HasDatabaseName("ix_group_lineage_links_moved_lineage_id");

                    b.HasIndex("SourceGroupId")
                        .HasDatabaseName("ix_group_lineage_links_source_group_id");

                    b.HasIndex("TargetGroupId")
                        .HasDatabaseName("ix_group_lineage_links_target_group_id");

                    b.ToTable("group_lineage_links", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_members_group_id_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<int>("ExpenseCount")
                        .HasColumnType("integer")
                        .HasColumnName("expense_count");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("ImportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("imported_by_user_id");

                    b.Property<DateTimeOffset?>("RolledBackAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rolled_back_at");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SourceLabel")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("source_label");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_import_batches_group_id");

                    b.HasIndex("ImportedByUserId")
                        .HasDatabaseName("ix_import_batches_imported_by_user_id");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("auth");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset?>("FailingSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failing_since");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("P256dh")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_receipts_content_hash");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.RecurringExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_on");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("integer")
                        .HasColumnName("max_occurrences");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<Guid>("PaidByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_member_id");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<string>("SplitTemplateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("split_template_json");

                    b.Property<int>("SplitType")
                        .HasColumnType("integer")
                        .HasColumnName("split_type");

                    b.Property<DateTimeOffset>("StartsOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_on");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_recurring_expenses");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_recurring_expenses_group_id");

                    b.HasIndex("IsPaused", "NextRunAt")
                        .HasDatabaseName("ix_recurring_expenses_is_paused_next_run_at");

                    b.ToTable("recurring_expenses", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountInBaseCurrency")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount_in_base_currency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<Guid>("FromMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_member_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastWriterDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_writer_device_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("OriginLineageId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_lineage_id");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<DateTimeOffset>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<Guid>("ToMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_member_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_settlements");

                    b.HasIndex("FromMemberId")
                        .HasDatabaseName("ix_settlements_from_member_id");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_settlements_receipt_id");

                    b.HasIndex("ToMemberId")
                        .HasDatabaseName("ix_settlements_to_member_id");

                    b.HasIndex("GroupId", "ServerSeq")
                        .HasDatabaseName("ix_settlements_group_id_server_seq");

                    b.HasIndex("GroupId", "SettledAt")
                        .HasDatabaseName("ix_settlements_group_id_settled_at");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.SyncConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConflictingFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conflicting_fields_json");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("IncomingDeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("incoming_device_id");

                    b.Property<string>("IncomingPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("incoming_payload_json");

                    b.Property<Guid?>("IncomingUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("incoming_user_id");

                    b.Property<string>("IncomingVectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("incoming_vector_clock_json");

                    b.Property<int>("Resolution")
                        .HasColumnType("integer")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("StoredDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stored_device_id");

                    b.Property<string>("StoredPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stored_payload_json");

                    b.Property<string>("StoredVectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stored_vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_sync_conflicts");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_sync_conflicts_entity_type_entity_id");

                    b.HasIndex("GroupId", "Resolution")
                        .HasDatabaseName("ix_sync_conflicts_group_id_resolution");

                    b.ToTable("sync_conflicts", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.SyncLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CounterpartGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterpart_group_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("LineageId")
                        .HasColumnType("uuid")
                        .HasColumnName("lineage_id");

                    b.Property<int>("Operation")
                        .HasColumnType("integer")
                        .HasColumnName("operation");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<long>("ServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("server_seq");

                    b.Property<Guid?>("SourceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_group_id");

                    b.Property<Guid?>("SupersededBySnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_snapshot_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_sync_log");

                    b.HasIndex("LineageId")
                        .HasDatabaseName("ix_sync_log_lineage_id");

                    b.HasIndex("SupersededBySnapshotId")
                        .HasDatabaseName("ix_sync_log_superseded_by_snapshot_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_sync_log_entity_type_entity_id");

                    b.HasIndex("GroupId", "ServerSeq")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_log_group_id_server_seq");

                    b.ToTable("sync_log", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.SyncSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompactedEntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("compacted_entry_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CutoffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cutoff_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json");

                    b.Property<DateTimeOffset?>("TrimmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trimmed_at");

                    b.Property<long>("UpToServerSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("up_to_server_seq");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_clock_json");

                    b.HasKey("Id")
                        .HasName("pk_sync_snapshots");

                    b.HasIndex("GroupId", "UpToServerSeq")
                        .HasDatabaseName("ix_sync_snapshots_group_id_up_to_server_seq");

                    b.ToTable("sync_snapshots", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_subject");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<bool>("PrefersLightTheme")
                        .HasColumnType("boolean")
                        .HasColumnName("prefers_light_theme");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_subject");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ActivityLogEntry", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_activity_log_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.CategoryRule", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_rules_categories_category_id");

                    b.HasOne("SplitEverything.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_rules_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Device", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Expense", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_categories_category_id");

                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany("Expenses")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_groups_group_id");

                    b.HasOne("SplitEverything.Domain.Entities.GroupMember", "PaidByMember")
                        .WithMany()
                        .HasForeignKey("PaidByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_group_members_paid_by_member_id");

                    b.HasOne("SplitEverything.Domain.Entities.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_receipts_receipt_id");

                    b.HasOne("SplitEverything.Domain.Entities.RecurringExpense", "RecurringExpense")
                        .WithMany()
                        .HasForeignKey("RecurringExpenseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_recurring_expenses_recurring_expense_id");

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("PaidByMember");

                    b.Navigation("Receipt");

                    b.Navigation("RecurringExpense");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseComment", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.GroupMember", "AuthorMember")
                        .WithMany()
                        .HasForeignKey("AuthorMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_comments_group_members_author_member_id");

                    b.HasOne("SplitEverything.Domain.Entities.Expense", "Expense")
                        .WithMany("Comments")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_comments_expenses_expense_id");

                    b.HasOne("SplitEverything.Domain.Entities.ExpenseComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_expense_comments_expense_comments_parent_comment_id");

                    b.Navigation("AuthorMember");

                    b.Navigation("Expense");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseItem", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Expense", "Expense")
                        .WithMany("Items")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_items_expenses_expense_id");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseItemShare", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.ExpenseItem", "ExpenseItem")
                        .WithMany("Shares")
                        .HasForeignKey("ExpenseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_item_shares_expense_items_expense_item_id");

                    b.HasOne("SplitEverything.Domain.Entities.GroupMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_item_shares_group_members_member_id");

                    b.Navigation("ExpenseItem");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseRevision", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Expense", "Expense")
                        .WithMany("History")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_revisions_expenses_expense_id");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseSplit", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Expense", "Expense")
                        .WithMany("Splits")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_splits_expenses_expense_id");

                    b.HasOne("SplitEverything.Domain.Entities.GroupMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_splits_group_members_member_id");

                    b.Navigation("Expense");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.GroupInvite", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany("Invites")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_invites_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("SplitEverything.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_members_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.User", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.RecurringExpense", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_expenses_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.GroupMember", "FromMember")
                        .WithMany()
                        .HasForeignKey("FromMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_group_members_from_member_id");

                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany("Settlements")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_groups_group_id");

                    b.HasOne("SplitEverything.Domain.Entities.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_settlements_receipts_receipt_id");

                    b.HasOne("SplitEverything.Domain.Entities.GroupMember", "ToMember")
                        .WithMany()
                        .HasForeignKey("ToMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_group_members_to_member_id");

                    b.Navigation("FromMember");

                    b.Navigation("Group");

                    b.Navigation("Receipt");

                    b.Navigation("ToMember");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.SyncLogEntry", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_log_groups_group_id");

                    b.HasOne("SplitEverything.Domain.Entities.SyncSnapshot", "SupersededBySnapshot")
                        .WithMany()
                        .HasForeignKey("SupersededBySnapshotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sync_log_sync_snapshots_superseded_by_snapshot_id");

                    b.Navigation("Group");

                    b.Navigation("SupersededBySnapshot");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.SyncSnapshot", b =>
                {
                    b.HasOne("SplitEverything.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_snapshots_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Expense", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("History");

                    b.Navigation("Items");

                    b.Navigation("Splits");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.ExpenseItem", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.Group", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("SplitEverything.Domain.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Memberships");

                    b.Navigation("PushSubscriptions");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
